---
- name: "Paso 4: Despliegue de Máquina Virtual"
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection

  vars:
    resource_group: "Horsebit_Productivo_rg"
    location: "spaincentral"
    nic_name: "NIC_Web_01"
    vm_name: "VM_Web_01"
    admin_user: "azureuser"

  tasks:
    - name: 1. Crear Máquina Virtual Ubuntu 22.04
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        vm_size: "Standard_B1ms"
        location: "{{ location }}"
        admin_username: "{{ admin_user }}"
        ssh_password_enabled: false
        ssh_public_keys:
          - path: "/home/{{ admin_user }}/.ssh/authorized_keys"
            key_data: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        network_interfaces:
          - "{{ nic_name }}"
        image:
          publisher: Canonical
          offer: 0001-com-ubuntu-server-jammy
          sku: 22_04-lts
          version: latest
