[productivo]
158.158.121.133 ansible_user=azureuser ansible_ssh_pass='ServerAzureHorsebitNuevo1234' ansible_become_password='ServerAzureHorsebitNuevo1234' ansible_ssh_common_args='-o StrictHostKeyChecking=no'
